apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: place-tale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tanmaykumarchaurasia/place-tale-teller:backend-v3
          ports:
            - containerPort: 3030
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/place_tale

