apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: place-tale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: tanmaykumarchaurasia/place-tale-teller:frontend-v3
          ports:
            - containerPort: 8080

